/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.unesp.rc.hotelmood.visao;

import br.unesp.rc.hotelmood.modelo.Avaliacao;
import br.unesp.rc.hotelmood.modelo.Cliente;
import br.unesp.rc.hotelmood.modelo.Comentario;
import br.unesp.rc.hotelmood.modelo.Hotel;
import br.unesp.rc.hotelmood.modelo.Proprietario;
import br.unesp.rc.hotelmood.modelo.ServicosHotel;
import br.unesp.rc.hotelmood.repositorio.AvaliacaoRepositorio;
import br.unesp.rc.hotelmood.repositorio.HotelRepositorio;
import br.unesp.rc.hotelmood.utilitario.AnalisadorSentimento;
import br.unesp.rc.hotelmood.utilitario.GeradorDrools;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAvaliar = new javax.swing.JButton();
        btnCarregarHoteis = new javax.swing.JButton();
        btnImprimirHoteis = new javax.swing.JButton();
        btnCarregarAvaliacoes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu Principal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnAvaliar.setText("Fazer Avaliação");
        btnAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliarActionPerformed(evt);
            }
        });

        btnCarregarHoteis.setText("Carregar Hotéis");
        btnCarregarHoteis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarHoteisActionPerformed(evt);
            }
        });

        btnImprimirHoteis.setText("Imprimir Hotéis");
        btnImprimirHoteis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirHoteisActionPerformed(evt);
            }
        });

        btnCarregarAvaliacoes.setText("Carregar Exemplos Avaliações");
        btnCarregarAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarAvaliacoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAvaliar, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(btnCarregarAvaliacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnImprimirHoteis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCarregarHoteis, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCarregarHoteis, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(btnAvaliar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnImprimirHoteis, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(btnCarregarAvaliacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarregarHoteisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarHoteisActionPerformed
        // TODO add your handling code here:
        ServicosHotel s1 = new ServicosHotel(true, false, false, false);
        ServicosHotel s2 = new ServicosHotel(false, true, true, false);
        ServicosHotel s3 = new ServicosHotel(true, false, false, true);
        ServicosHotel s4 = new ServicosHotel(true, true, false, true);
        ServicosHotel s5 = new ServicosHotel(true, true, true, true);

        Proprietario prop1 = new Proprietario(true, 100, "Rebeca", 39);
        Proprietario prop2 = new Proprietario(false, 50, "Linda", 57);
        Proprietario prop3 = new Proprietario(true, 20, "Romario", 24);
        Proprietario prop4 = new Proprietario(true, 20, "Fabricio", 24);
        Proprietario prop5 = new Proprietario(true, 20, "Orlando", 24);

        Hotel h1 = new Hotel("Pegasus", "Rua 1", prop1, s1);
        Hotel h2 = new Hotel("Capricornio", "Rua 2", prop2, s2);
        Hotel h3 = new Hotel("Aquarius", "Rua 3", prop3, s3);
        Hotel h4 = new Hotel("Bosque dos Eucaliptos", "Rua 4", prop4, s4);
        Hotel h5 = new Hotel("Campo dos Alemaes", "Rua 5", prop5, s5);

        HotelRepositorio hrepositorio = new HotelRepositorio();
        hrepositorio.adicionar(h1);
        hrepositorio.adicionar(h2);
        hrepositorio.adicionar(h3);
        hrepositorio.adicionar(h4);
        hrepositorio.adicionar(h5);

        JOptionPane.showMessageDialog(this, "Dados dos hoteis carregado com sucesso!", "Menssagem", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnCarregarHoteisActionPerformed

    private void btnImprimirHoteisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirHoteisActionPerformed
        // TODO add your handling code here:
        HotelRepositorio hrepositorio = new HotelRepositorio();
        hrepositorio.imprimir();
    }//GEN-LAST:event_btnImprimirHoteisActionPerformed

    private void btnAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaliarActionPerformed
        // TODO add your handling code here:
        JFrame f = new JFrameAvaliar();
        f.pack();
        f.setVisible(true);
        f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnAvaliarActionPerformed

    private void btnCarregarAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarAvaliacoesActionPerformed
        // TODO add your handling code here:
        HotelRepositorio hrepositorio = new HotelRepositorio();

        if (hrepositorio.getHoteis().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Necessario carregar hoteis primeiro", "Erro", JOptionPane.ERROR_MESSAGE);

        } else {

            Comentario c1 = new Comentario("Os hóspedes gostaram dos quartos amplos, limpos e modernos, embora alguns tenham dito que a manutenção poderia ser melhorada · "
                    + "Os banheiros eram amplos e limpos", new Date());

            Comentario c2 = new Comentario("Fui tratado com muita falta de educação e falta de empatia. Após um dia de trabalho, pedi uma comida pelo iFood e pedi \n"
                    + "pra entregar no quarto (como em qualquer hotel normal). Se não bastasse não entregar e não saber explicar o motivo, \n"
                    + "pois eu pedi pro serviço de quarto entregar (e não pro motoboy subir, por óbvio), o rapaz cabeludo da recepção \n"
                    + "ficou debochando e fazendo ironia, dizendo pra eu reclamar com a gerente, muito mal educado e descompromissado com a \n"
                    + "satisfação do cliente.", new Date());

            Comentario c3 = new Comentario("Me hospedei na suíte Rubi e achei o quarto amplo, com uma cama grande e confortável. O banheiro também era espaçoso, \n"
                    + "com chuveiro de pressão forte. O quarto estava próximo à piscina e oferecia uma vista para o Cristo Redentor. \n"
                    + "O café da manhã era bem completo, e o atendimento dos funcionários muito simpático, inclusive dando dicas de locais \n"
                    + "para conhecer na cidade. Com certeza, o Hotel Bandeirantes será minha primeira opção ao pensar em retornar ao Rio.", new Date());

            Comentario c4 = new Comentario("Cafe da manhã e atendimento excepcional e muito próximo à praia. Quartos espaçoso Banheiros com chuveiro muito bom. \n"
                    + "Da janela via se o cristo redentor. Hotel silencioso. Recepção excepcional. Rua calma para transitar a qualquer hora,\n"
                    + "proximo a restaurantes,farmácia,lojas,lotérica,sorveterias e supermercados.", new Date());

            Comentario c5 = new Comentario("Café da manhã bem fraco, com poucas opções\n"
                    + "Serviço de quarto só funciona se vc pedir e mesmo assim não trocaram as minhas toalhas, nem de rosto e nem de banho.\n"
                    + "OS quartos tem poucas tomadas e nenhuma perto da cama, o Ar condicionado é bem fraco, deixei com 17º e mesmo assim não gelou o suficiente, e a temperatura externa era apenas de 26º, o que é um dia ameno para o verão carioca.\n"
                    + "O atendimento foi bom, os funcionários foram educados e simpáticos em toda a estadia.", new Date());

            Cliente p1 = new Cliente("brendo@gmail.com", "(12)98734758", "Brendo", 18);
            Cliente p2 = new Cliente("rafael@gmail.com", "(19)953546643", "Rafael", 21);
            Cliente p3 = new Cliente("leo@gmail.com", "(11)97162548", "Leonardo", 19);
            Cliente p4 = new Cliente("bia@gmail.com", "(11)981620394", "Bia", 20);
            Cliente p5 = new Cliente("erick@gmail.com", "(11)162538273", "Erick", 19);
            
            Hotel h1 = hrepositorio.getHoteis().get(0);
            Hotel h2 = hrepositorio.getHoteis().get(1);
            Hotel h3 = hrepositorio.getHoteis().get(2);
            Hotel h4 = hrepositorio.getHoteis().get(3);
            Hotel h5 = hrepositorio.getHoteis().get(4);
            
            Avaliacao a1 = new Avaliacao(p1, h1, c1);
            Avaliacao a2 = new Avaliacao(p2, h2, c2);
            Avaliacao a3 = new Avaliacao(p3, h3, c3);
            Avaliacao a4 = new Avaliacao(p4, h4, c4);
            Avaliacao a5 = new Avaliacao(p5, h5, c5);
            
            AvaliacaoRepositorio arepositorio = new AvaliacaoRepositorio();
            arepositorio.adicionar(a1);
            arepositorio.adicionar(a2);
            arepositorio.adicionar(a3);
            arepositorio.adicionar(a4);
            arepositorio.adicionar(a5);
            
            AnalisadorSentimento analisador = new AnalisadorSentimento("src/main/java/br/unesp/rc/hotelmood/modeloIA/datasetsentimento.bin");
            a1.setSentimento(analisador.analisar(c1.getMenssagem()));
            a2.setSentimento(analisador.analisar(c2.getMenssagem()));
            a3.setSentimento(analisador.analisar(c3.getMenssagem()));
            a4.setSentimento(analisador.analisar(c4.getMenssagem()));
            a5.setSentimento(analisador.analisar(c5.getMenssagem()));
            
            GeradorDrools drools = new GeradorDrools("rules/Sample.drl");
            drools.configurar();
            drools.adicionarObjeto(a1);
            drools.adicionarObjeto(a2);
            drools.adicionarObjeto(a3);
            drools.adicionarObjeto(a4);
            drools.adicionarObjeto(a5);
            drools.executarRegra();
            
            JOptionPane.showMessageDialog(this, "Dados das avaliacoes carregado com sucesso!", "Menssagem", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnCarregarAvaliacoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvaliar;
    private javax.swing.JButton btnCarregarAvaliacoes;
    private javax.swing.JButton btnCarregarHoteis;
    private javax.swing.JButton btnImprimirHoteis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
